//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class AuthClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    login(req: LoginRequest): Promise<LoginResponse> {
        let url_ = this.baseUrl + "/api/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(req);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<LoginResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LoginResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LoginResponse>(null as any);
    }

    register(req: RegisterRequest): Promise<RegisterResponse> {
        let url_ = this.baseUrl + "/api/auth/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(req);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<RegisterResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RegisterResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RegisterResponse>(null as any);
    }
}

export class RealtimeSubscriptionsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    listenFarm(farmId: string, connectionId: string | undefined): Promise<RealtimeListenResponseOfFarmRealtimePayload> {
        let url_ = this.baseUrl + "/api/realtime/farm/{farmId}/listen?";
        if (farmId === undefined || farmId === null)
            throw new globalThis.Error("The parameter 'farmId' must be defined.");
        url_ = url_.replace("{farmId}", encodeURIComponent("" + farmId));
        if (connectionId === null)
            throw new globalThis.Error("The parameter 'connectionId' cannot be null.");
        else if (connectionId !== undefined)
            url_ += "connectionId=" + encodeURIComponent("" + connectionId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListenFarm(_response);
        });
    }

    protected processListenFarm(response: Response): Promise<RealtimeListenResponseOfFarmRealtimePayload> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RealtimeListenResponseOfFarmRealtimePayload;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RealtimeListenResponseOfFarmRealtimePayload>(null as any);
    }

    listenTurbine(farmId: string, turbineId: string, connectionId: string | undefined): Promise<RealtimeListenResponseOfFarmRealtimePayload> {
        let url_ = this.baseUrl + "/api/realtime/farm/{farmId}/turbine/{turbineId}/listen?";
        if (farmId === undefined || farmId === null)
            throw new globalThis.Error("The parameter 'farmId' must be defined.");
        url_ = url_.replace("{farmId}", encodeURIComponent("" + farmId));
        if (turbineId === undefined || turbineId === null)
            throw new globalThis.Error("The parameter 'turbineId' must be defined.");
        url_ = url_.replace("{turbineId}", encodeURIComponent("" + turbineId));
        if (connectionId === null)
            throw new globalThis.Error("The parameter 'connectionId' cannot be null.");
        else if (connectionId !== undefined)
            url_ += "connectionId=" + encodeURIComponent("" + connectionId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListenTurbine(_response);
        });
    }

    protected processListenTurbine(response: Response): Promise<RealtimeListenResponseOfFarmRealtimePayload> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RealtimeListenResponseOfFarmRealtimePayload;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RealtimeListenResponseOfFarmRealtimePayload>(null as any);
    }
}

export class WindmillWebClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    getWindmills(farmId: string): Promise<Windmill[]> {
        let url_ = this.baseUrl + "/api/farms/{farmId}/windmills";
        if (farmId === undefined || farmId === null)
            throw new globalThis.Error("The parameter 'farmId' must be defined.");
        url_ = url_.replace("{farmId}", encodeURIComponent("" + farmId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetWindmills(_response);
        });
    }

    protected processGetWindmills(response: Response): Promise<Windmill[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Windmill[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Windmill[]>(null as any);
    }

    getTelemetryHistory(farmId: string, turbineId: string, from: string | null | undefined, to: string | null | undefined, take: number | undefined): Promise<WindmillTelemetry[]> {
        let url_ = this.baseUrl + "/api/farms/{farmId}/windmills/{turbineId}/telemetry?";
        if (farmId === undefined || farmId === null)
            throw new globalThis.Error("The parameter 'farmId' must be defined.");
        url_ = url_.replace("{farmId}", encodeURIComponent("" + farmId));
        if (turbineId === undefined || turbineId === null)
            throw new globalThis.Error("The parameter 'turbineId' must be defined.");
        url_ = url_.replace("{turbineId}", encodeURIComponent("" + turbineId));
        if (from !== undefined && from !== null)
            url_ += "from=" + encodeURIComponent("" + from) + "&";
        if (to !== undefined && to !== null)
            url_ += "to=" + encodeURIComponent("" + to) + "&";
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetTelemetryHistory(_response);
        });
    }

    protected processGetTelemetryHistory(response: Response): Promise<WindmillTelemetry[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as WindmillTelemetry[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WindmillTelemetry[]>(null as any);
    }

    getAlerts(farmId: string, turbineId: string, take: number | undefined): Promise<Alert[]> {
        let url_ = this.baseUrl + "/api/farms/{farmId}/windmills/{turbineId}/alerts?";
        if (farmId === undefined || farmId === null)
            throw new globalThis.Error("The parameter 'farmId' must be defined.");
        url_ = url_.replace("{farmId}", encodeURIComponent("" + farmId));
        if (turbineId === undefined || turbineId === null)
            throw new globalThis.Error("The parameter 'turbineId' must be defined.");
        url_ = url_.replace("{turbineId}", encodeURIComponent("" + turbineId));
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAlerts(_response);
        });
    }

    protected processGetAlerts(response: Response): Promise<Alert[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Alert[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Alert[]>(null as any);
    }

    sendCommand(farmId: string, turbineId: string, req: CommandRequest): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/farms/{farmId}/windmills/{turbineId}/command";
        if (farmId === undefined || farmId === null)
            throw new globalThis.Error("The parameter 'farmId' must be defined.");
        url_ = url_.replace("{farmId}", encodeURIComponent("" + farmId));
        if (turbineId === undefined || turbineId === null)
            throw new globalThis.Error("The parameter 'turbineId' must be defined.");
        url_ = url_.replace("{turbineId}", encodeURIComponent("" + turbineId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(req);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSendCommand(_response);
        });
    }

    protected processSendCommand(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    getOperatorActions(farmId: string, turbineId: string, take: number | undefined): Promise<OperatorAction[]> {
        let url_ = this.baseUrl + "/api/farms/{farmId}/windmills/{turbineId}/actions?";
        if (farmId === undefined || farmId === null)
            throw new globalThis.Error("The parameter 'farmId' must be defined.");
        url_ = url_.replace("{farmId}", encodeURIComponent("" + farmId));
        if (turbineId === undefined || turbineId === null)
            throw new globalThis.Error("The parameter 'turbineId' must be defined.");
        url_ = url_.replace("{turbineId}", encodeURIComponent("" + turbineId));
        if (take === null)
            throw new globalThis.Error("The parameter 'take' cannot be null.");
        else if (take !== undefined)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetOperatorActions(_response);
        });
    }

    protected processGetOperatorActions(response: Response): Promise<OperatorAction[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as OperatorAction[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<OperatorAction[]>(null as any);
    }

    connect(): Promise<void> {
        let url_ = this.baseUrl + "/api/farms/sse";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processConnect(_response);
        });
    }

    protected processConnect(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface LoginResponse {
    token?: string;
    userId?: string;
    nickname?: string;
    role?: string;
}

export interface LoginRequest {
    nickname?: string;
    password?: string;
}

export interface RegisterResponse {
    userId?: string;
    nickname?: string;
    role?: string;
}

export interface RegisterRequest {
    nickname?: string;
    password?: string;
    role?: string;
}

/** Returned by subscribe endpoints so the client knows which SSE group to listen on. */
export interface RealtimeListenResponse {
    group?: string;
}

/** Returned by subscribe endpoints with initial data. The client receives the current state immediately and knows which SSE group to listen on for subsequent updates. */
export interface RealtimeListenResponseOfFarmRealtimePayload extends RealtimeListenResponse {
    data?: FarmRealtimePayload | undefined;
}

export interface FarmRealtimePayload {
    telemetry?: WindmillTelemetry[];
    alerts?: Alert[];
}

export interface WindmillTelemetry {
    id?: string;
    farmId?: string;
    windmillId?: string;
    timestamp?: string;
    windSpeed?: number;
    windDirection?: number;
    ambientTemperature?: number;
    rotorSpeed?: number;
    powerOutput?: number;
    nacelleDirection?: number;
    bladePitch?: number;
    generatorTemp?: number;
    gearboxTemp?: number;
    vibration?: number;
    status?: string;
}

export interface Alert {
    id?: string;
    farmId?: string;
    windmillId?: string;
    timestamp?: string;
    severity?: string;
    code?: string;
    message?: string;
}

export interface Windmill {
    id?: string;
    farmId?: string;
    name?: string;
    location?: string;
}

export interface CommandRequest {
    action?: string;
    payload?: any;
}

export interface OperatorAction {
    id?: string;
    farmId?: string;
    windmillId?: string;
    timestamp?: string;
    operatorUserId?: string;
    commandType?: string;
    payloadJson?: string;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}